title: icansecurethat.com
author: icansecurethat
  name: icansecurethat
description: >- 
  Personal cybersecurity blog and research posts.

plugins:
 - jekyll-feed
 - jekyll-seo-tag

exclude:
 - LICENSE.txt
 - README.md
 - '*.gemspec'
 - '*.gem'
